edurange_refactored/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
import os
import json
from datetime import datetime

from flask import (
    Blueprint,
    abort,
    flash,
    redirect,
    render_template,
    request,
    session,
    send_from_directory,
    url_for,
)
from flask_login import login_required

from edurange_refactored.extensions import db
from edurange_refactored.notification_utils import NotifyCapture
from edurange_refactored.user.forms import (
    GroupForm,
    addUsersForm,
    changeEmailForm,
    deleteGroupForm,
    makeScenarioForm,
    manageInstructorForm,
    modScenarioForm,
    notifyDeleteForm,
    scenarioResponseForm,
)

from ..csv_utils import readCSV, groupCSV
from ..form_utils import process_request
from ..graph_utils import getGraph
from ..role_utils import (
    get_roles,
    scenario_exists,
    student_has_access,
    user_is_admin_and_instructor,
    user_is_admin,
    user_is_instructor
)
from ..scenario_utils import gen_chat_names, identify_state, identify_type, populate_catalog
from ..utils import (
    check_role_view,
    displayCorrectAnswers,
    displayProgress,
    flash_errors,
    getScore,
    responseProcessing,
    getResponses,
    responseSelector,
    tempMaker,
    queryPolish,
    questionReader,
)

from .models import GroupUsers, ScenarioGroups, Scenarios, StudentGroups, User, Responses, Notification


blueprint = Blueprint(
    "dashboard", __name__, url_prefix="/dashboard", static_folder="../static"
)

@blueprint.route("/")
@login_required
def student():
    """List members."""
    # Queries for the user dashboard
    db_ses = db.session
    currentUserId = session.get("_user_id")

    userInfo = db_ses.query(User.id, User.username, User.email).filter(User.id == currentUserId)

    groups = db_ses.query(StudentGroups.id, StudentGroups.name, GroupUsers) \
        .filter(GroupUsers.user_id == currentUserId) \
        .filter(GroupUsers.group_id == StudentGroups.id)

    scenarioTable = (
        db_ses.query(
            Scenarios.id,
            Scenarios.name.label("sname"),
            Scenarios.description.label("type"),
            StudentGroups.name.label("gname"),
            User.username.label("iname"),
        )
        .filter(GroupUsers.user_id == currentUserId)
        .filter(StudentGroups.id == GroupUsers.group_id)
        .filter(User.id == StudentGroups.owner_id)
        .filter(ScenarioGroups.group_id == StudentGroups.id)
        .filter(Scenarios.id == ScenarioGroups.scenario_id)
    )

    return render_template(
        "dashboard/student.html",
        userInfo=userInfo,
        groups=groups,
        scenarioTable=scenarioTable,
    )


@blueprint.route("/account_management", methods=['GET', 'POST'])
@login_required
def account():
    db_ses = db.session
    userId = session.get('_user_id')

    user = db_ses.query(User).filter(User.id == userId).first()

    if user.is_admin or user.is_instructor:
        groupCount = db_ses.query(StudentGroups.id).filter(StudentGroups.owner_id == user.get_id()).count()
        label = "Owner Of"
    elif user.is_static:
        # In this case, groupCount is the name of the group this user is a static member of
        groupCount = db_ses.query(StudentGroups.name) \
            .filter(StudentGroups.id == GroupUsers.group_id, GroupUsers.user_id == user.get_id()) \
            .first()[0]
        label = "Temp. Member Of"
    else:
        groupCount = db_ses.query(StudentGroups.id) \
            .filter(StudentGroups.id == GroupUsers.group_id, GroupUsers.user_id == user.get_id()) \
            .count()
        label = "Member Of"

    if request.method == 'GET':
        emailForm = changeEmailForm()

        return render_template(
            'dashboard/account_management.html',
            emailForm=emailForm,
            groupCount=groupCount,
            label=label,
            user=user
        )

    # POST request
    cE = changeEmailForm(request.form)
    if cE.validate_on_submit():
        address = cE.address.data
        user.update(email=address, is_static=False)
        flash(f'Account email address successfully changed to: {address}', 'success')
    else:
        flash_errors(cE)

    return redirect(url_for('dashboard.account'))


@blueprint.route("/admin", methods=["GET", "POST"])
@login_required
def admin():
    """List of all students and groups. Group, student, and instructor management forms"""
    user_is_admin()

    db_ses = db.session
    users_per_group = {}

    students = db_ses.query(User.id, User.username, User.email, User.is_static).filter(User.is_instructor == False)
    instructors = db_ses.query(User.id, User.username, User.email).filter(User.is_instructor == True)
    groups = StudentGroups.query.all()

    groupNames = [group.name for group in groups]

    for name in groupNames:
        users_per_group[name] = db_ses.query(User.id, User.username, User.email, User.is_static).filter(
            StudentGroups.name == name,
            StudentGroups.id == GroupUsers.group_id,
            GroupUsers.user_id == User.id,
        )

    if request.method == "GET":
        groupMaker = GroupForm()
        userAdder = addUsersForm()
        instructorManager = manageInstructorForm()
        groupEraser = deleteGroupForm()

        return render_template(
            "dashboard/admin.html",
            groupMaker=groupMaker,
            userAdder=userAdder,
            instructorManager=instructorManager,
            groups=groups,
            students=students,
            instructors=instructors,
            usersPGroup=users_per_group,
            groupEraser=groupEraser
        )

    # POST request
    ajax = process_request(request.form)
    if ajax:
        temp = ajax[0]
        if temp == 'utils/create_group_response.html':
            if len(ajax) == 1:
                return render_template(temp)
            elif len(ajax) < 4:
                return render_template(temp, group=ajax[1], users=ajax[2])

            return render_template(temp, group=ajax[1], users=ajax[2], pairs=ajax[3])
        elif temp == 'utils/manage_student_response.html':
            if len(ajax) == 1:
                return render_template(temp)

            return render_template(temp, group=ajax[1], users=ajax[2])

    return redirect(url_for("dashboard.admin"))


@blueprint.route("/instructor", methods=["GET", "POST"])
@login_required
def instructor():
    """List of an instructors groups"""
    user_is_instructor()

    userId = session.get("_user_id")
    db_ses = db.session

    students = db_ses.query(User.id, User.username, User.email, User.is_static).filter(User.is_instructor == False)
    groups = db_ses.query(
        StudentGroups.id, StudentGroups.name, StudentGroups.code
    ).filter(StudentGroups.owner_id == userId)
    users_per_group = {}

    for group in groups:
        users_per_group[group.name] = db_ses.query(User.id, User.username, User.email, User.is_static).filter(
            StudentGroups.name == group.name,
            StudentGroups.id == GroupUsers.group_id,
            GroupUsers.user_id == User.id,
        )

    if request.method == "GET":
        groupMaker = GroupForm()
        userAdder = addUsersForm()

        return render_template(
            "dashboard/instructor.html",
            groupMaker=groupMaker,
            userAdder=userAdder,
            students=students,
            groups=groups,
            usersPGroup=users_per_group,
        )

    # POST request
    ajax = process_request(request.form)
    if ajax:
        temp = ajax[0]
        if temp == 'utils/create_group_response.html':
            if len(ajax) == 1:
                return render_template(temp)
            elif len(ajax) < 4:
                return render_template(temp, group=ajax[1], users=ajax[2])

            return render_template(temp, group=ajax[1], users=ajax[2], pairs=ajax[3])
        elif temp == 'utils/manage_student_response.html':
            if len(ajax) == 1:
                return render_template(temp)

            return render_template(temp, group=ajax[1], users=ajax[2])

    return redirect(url_for("dashboard.instructor"))

@blueprint.route("/notification", methods=["GET", "POST"])
@login_required
def notification():
    
    # if request.method == "POST": process_request(request.form)
    notifications_raw = Notification.query.all()
    
    notifications_processed = []
    for notif in notifications_raw:
        notif_serialized = {
            "id": notif.id,
            "date": notif.date.isoformat(),
            "detail": notif.detail
        }
        notifications_processed.append(notif_serialized)

    # deleteNotify = notifyDeleteForm()
    notifications_export = json.dumps(notifications_processed)

    return render_template(
        "dashboard/notification.html",
        notifications=notifications_export
        # deleteNotify=deleteNotify
    )

@blueprint.route("/student_scenario/<i>", methods=["GET", "POST"])
@login_required
def student_scenario(i):
    if student_has_access(i):
        if scenario_exists(i):
            status, owner, desc, s_type, s_name, u_name, pw, guide, questions = tempMaker(i, "stu")
            # query = db_ses.query(User.id)\
            #    .filter(Responses.scenario_id == i).filter(Responses.user_id == User.id).all()
            uid = session.get("_user_id")
            # att = db_ses.query(Scenarios.attempt).filter(Scenarios.id == i).first()
            addresses = identify_state(s_name, status)
            # query = db_ses.query(Responses.user_id, Responses.attempt, Responses.question, Responses.points,
            #                     Responses.student_response).filter(Responses.scenario_id == i)\
            #    .filter(Responses.user_id == uid).filter(Responses.attempt == att).all()
            if request.method == "GET":
                scenarioResponder = scenarioResponseForm()
                aList = displayCorrectAnswers(s_name, uid)
                progress = displayProgress(i, uid)
                example = -1

edurange_refactored/templates/dashboard/account_management.html
{% extends "layout.html" %}
{% block content %}
   <link
           rel="stylesheet"
           type="text/css"
           href="{{ url_for('static', filename='build/accountmgmt.bundle.css') }}"
   />
<main class="student">
 <div id="accountmgmt"></div>
</div>
</main>


{% endblock %}


{% block  js %}
<script src="/static/build/accountmgmt.bundle.js"></script>
{% endblock %}

edurange_refactored/templates/dashboard/catalog.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <h1>Choose a Scenario to Create</h1>
    </div>
<div class="container">
    <form action="/dashboard/make_scenario" method="post">
    {{ form.csrf_token }}
        <input class="form-control" name="scenario_name" type="text" id="scenario_name" placeholder="Scenario Name">
        <select name="scenario_group" title="Group">
            {% for group in groups %}
                <option value="{{group.name}}" SELECTED>{{group.name}}</option>
            {% endfor %}
        </select>
    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th> Scenario </th>
            <th> Description </th>
            <th> Action </th>
        </tr>
        </thead>
    <tbody>
        {% for s in scenarios %}
            <tr>
                <td> {{ s.name }}</td>
                <td> {{ s.description }}</td>
                <td>
                    <input class="btn btn-dark" type="submit" value="Create"
                           name={{ s.name }} id="new_scenario" />
                </td>
            </tr>
        {% endfor  %}
    </tbody>
    </table>
    </form>
</div>

{%  endblock %}

edurange_refactored/templates/dashboard/create_scenario.html
{% extends "layout.html" %}
{% block content %}
   <link
           rel="stylesheet"
           type="text/css"
           href="{{ url_for('static', filename='build/create_scenario.bundle.css') }}"
   />
<main class="student">
 <div id="createScenario" ></div>
</div>
</main>


{% endblock %}


{% block  js %}
<script src="/static/build/create_scenario.bundle.js"></script>
{% endblock %}

edurange_refactored/templates/dashboard/graphs.html
{% if graph %}
{{ graph | safe}}
{% endif %}

{% with messages = get_flashed_messages(with_categories=true) %} {% if messages %}
<div class="col mb-0" id="flashed">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} mb-0">
        <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
        {{ message }}
    </div><!-- end .alert -->
    {% endfor %}
</div><!-- end col -->
{% endif %} {% endwith %}

edurange_refactored/templates/dashboard/notification.html
{% extends "layout.html" %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='build/Notification.bundle.css') }}" />
<main class="notification-class">
    <div id="notification-page" notifications="{{notifications}}">
    </div>
</main>
{% endblock %}

{% block js %}
<script src="/static/build/Notification.bundle.js"></script>
{% endblock %}

edurange_refactored/templates/dashboard/notification_original.html
{% extends "layout.html" %}
{% block content %}

<!-- scripts for notification page -->
<p></p>
<div class="container">
    <form method="POST">
        {{ deleteNotify.csrf_token }}
        <input name="clearButton" class="btn btn-dark" type="submit" value="Clear all notifications"/>
    </form>
    <p></p>
    <table class="table">
        <caption>Table of Notification history</caption>
        <thead class="thead-dark">
            <tr>
                <th data-sort="string"scope="col">Notification</th>
                <th data-sort="float" data-sort-default="desc" scope="col">Date</th>
            </tr>
        </thead>
        <tbody>
        {% for notification in notifications %}
            <tr>
                <td>{{notification.detail}}</td>
                <td>{{notification.date}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

edurange_refactored/templates/dashboard/progress_dev.html
{% extends "layout.html" %}
{% block content %}
<style>
    h1 {
        color: black;
    }

    div.scroll {
        margin: 4px, 4px;
        /* padding: 20px; */
        background-color: #e9ecef;
        width: 100%;
        overflow: auto;
        white-space: nowrap;
    }
</style>

<body>
    <div class="jumbotron">
        <div id="graphSelector">
            <h5>Select a Student and Scenario to Graph:</h5>

            <form id="form" action="/dashboard/progress_dev" method="POST" role="form">
                {{ form.csrf_token }}
                <label for="student">Students</label>
                <select id="student" name="student" title="Students" onchange="updateDropdown('#student', '#scenario')">
                    <option selected>select</option>
                    {% for st in students %}
                    <option>{{ st }}</option>
                    {% endfor %}
                </select>

                <label for="scenario">Scenarios</label>                
                <select id="scenario" name="scenario" title="Scenarios" onchange="updateDropdown('#scenario', '#student')">
                    <option selected>select</option>
                    {% for sc in scenarios %}
                    <option>{{ sc }}</option>
                    {% endfor %}
                </select>
                <input id="generate" name="generate" class="btn btn-dark" type="submit" value="Generate"/>
            </form>
            <br>
        </div>
    </div>

    <div class="scroll" , id="Graph Window">
        {{ graph_output|safe }}
    </div>
</body>

<script>
    const updateDropdown = (source_id, target_id) => { 
        $(target_id).load(
            '/dashboard/progress_dev', {
                csrf_token: $('#csrf_token').attr('value'),
                dropdown_update: true,
                source_id: source_id,
                source_selection: $(source_id).val(),
                target_selection: $(target_id).val()
        });
    }
</script>
{% endblock %}

edurange_refactored/templates/dashboard/scenarios.html
{% extends "layout.html" %}
{% block content %}
   <link
           rel="stylesheet"
           type="text/css"
           href="{{ url_for('static', filename='build/create_scenario.bundle.css') }}"
   />
<main class="student">
 <div id="createScenario" ></div>
</div>
</main>


{% endblock %}


{% block  js %}
<script src="/static/build/create_scenario.bundle.js"></script>
{% endblock %}

edurange_refactored/templates/dashboard/student_dashboard.html
{% extends "layout.html" %}
{% block content %}
    <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='build/student_dashboard.bundle.css') }}"
    />
<main class="student_dashboard">
  <div id="student_dashboard" userInfo={{userInfo}} groups={{groups}} scenarioTable="{{scenarioTable}}"></div>
</div>
</main>

{% endblock %}

{% block  js %}
<!-- development React scripts !!Replace with production scripts (below) for release!! -->
<script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>

<script src="/static/build/student_dashboard.bundle.js"></script>
{% endblock %}

edurange_refactored/templates/dashboard/student_scenario.html
<!-- | -->
{% extends "layout.html" %}
{% block content %}
    <div class="card bg-light">
        <div class="card-header">
            <h3>Name: {{ s_name }} </h3>
            <h3>Type: {{ s_type }} </h3>
        </div>
        <div class="card-body">
            <p><b>Description: </b>{{ desc }}</p>
            <p><b>ID: </b><span id="scenario_id">{{ id }}</span></p>
            <p><b>Status: </b> {{ status }} </p>
            <p><b>Instructor: </b> {{ owner }} </p>
            <p><b>Username: </b><span id="user">{{ u_name }}</span></p>
            <p><b>Password: </b> {{ pw }}</p>
            <!--<p><b> Connection Information: </b></p>-->
            {% for container in add %}
                {% if not add[container] %}
            <p><b> Connection Information: </b></p>
            <p>Container not found, something went wrong</p>
                {% elif ':' not in add[container] %}
            <p><b> Connection Information: </b></p>
            <p>Container address not found, is it running?</p>
                {% elif add[container][add[container].index(':') + 1 :] != "HIDDEN" %}
                    {% if s_type == "Web_Fu" %}
            <p><b> Connection: </b> <a target="_blank" href="https://{{add[container][:add[container].index(':')]}}:8443">WebFu</a></p>
                    {% else %}
                    <!-- <p> &nbsp;&nbsp;&nbsp; {{ container }} : {{ add[container] }}</p> -->
            <p style="margin-top: -10px;"><b>SSH Command: </b>
                <textarea cols="45" rows="1" id="sshCmd" readonly="readonly" style="overflow: auto;resize: none;position:relative;top:10px;">ssh {{ u_name }}@{{ add[container][:add[container].index(':')]}}  -p {{ add[container][add[container].index(':') + 1:] }}</textarea>
                <button class="btn btn-dark ml-2" id="copySSH"><i class="fa-solid fa-clipboard"></i> Copy </button>
                <script>function showSSHConsole() {
                    window.open("http://{{ add[container][:add[container].index(':')]}}:5050/ssh/host/{{add[container][:add[container].index(':')]}}/{{ add[container][add[container].index(':') + 1:] }}")
                }
                </script>
                <button class="btn btn-dark" id="openWebSSH" onClick="showSSHConsole()"><i class= "fa"> Open WebSSH Console</i></button>
                <!-- <div id="SSHConsoleContainer" style="display:none">
                    <iframe style="position:absolute;height:100%;width:100%;border:none" src= "http://{{ add[container][:add[container].index(':')]}}:5050/ssh/host/{{add[container][:add[container].index(':')]}}/{{ add[container][add[container].index(':') + 1:] }}/{{ u_name }}/{{ pw }}" ></iframe>
                </div> -->
            </p>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
        <ul class="nav nav-tabs mt-3 ml-3">
            <li class="nav-item active">
                <a href="#Responses" class="nav-link tab-pane fade show active" aria-controls="home" data-toggle="tab"  aria-selected="true">Responses</a>
                <!--{% for i in questions  %}
          <p>{{i}}</p>
        {% endfor %}-->
            </li>
            <li class="nav-item">
                <a href="#Guide" class="nav-link tab-pane show" data-toggle="tab" aria-selected="false">Guide</a>
            </li>
        </ul>
        <div class="tab-content">
            <!--<div class="card bg-light mb-3 mt-0 tab-pane show active" id="Responses">-->
            <div id="Responses" class="tab-pane show active">
                <div class="container mt-3">
                    <h3> Response Form </h3>
                    <h5 id="progress_q"> Questions Completed: {{ progress['questions'] }} / {{ progress['total_questions'] }} </h5>
                    <h5 id="progress_s"> Points Earned: {{ progress['score'] }} / {{ progress['total_score'] }} </h5>
                    <div class="card-body">
                        <div class="container">
                            {% for i in questions %}
                                <form method="POST" id="{{i}}">
                                    {{ srF.csrf_token }}
                                    <div class="form-group">
                                        {% if aList[i] == example%}
                                            <label id="question_ID{{i}}"><b>{{i}})</b> {{ questions[i] }} <i></i></label> <!-- added i element so replaceWith() works in all cases -->
                                        {% endif %}
                                        {% if aList[i] != 0 and aList[i] != example %}
                                            <label id="question_ID{{i}}"><b>{{i}})</b> {{ questions[i] }} <i class="fa-solid fa-check">Correct</i></label>
                                        {% endif %}
                                        {% if aList[i] == 0 %}
                                            <label id="question_ID{{i}}"><b>{{i}})</b> {{ questions[i] }} <i class="fa-solid fa-ban">Incorrect</i></label>
                                        {% endif %}
                                        <input class="form-control" type="hidden" name="scenario" value="{{ id }}" readonly>
                                        {#<input class="form-control" type="hidden" name="question" value="{{ i }}" readonly>#}
                                        <input type="text" name="response" id="input_ID{{i}}" class="form-control mb-2">
                                        <button class="btn btn-dark" value="{{ i }}" type="submit" name="question"> Submit </button>
					<br></br>
                                    </div>
                                </form>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <!--<div class="card bg-light mb-3 tab-pane fade" id="Guide">-->
            <div class="tab-pane" id="Guide">
                <div class="container mt-3">
                    <div class="card-body">
                        <div class="container">
                            {# <iframe src="{{ "data:text/html;charset=utf-8,%s" % guide }}" title="Guide" style="width:1100px; height:1000px;"></iframe> #}
                            <div id="GuideContent">
                                {{ guide|safe }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(document).ready(function() {
            {#{% for i in questions: %}
                //loop through all <input> ids
                $("#"+"{{i}}").keypress(function(event){
                    console.log("i");
                    var keycode = (event.keyCode ? event.keyCode : event.which);
                    if(keycode == '13'){
                        var questionText = $("#"+ "question_ID{{i}}").html();
                        //console.log($("#question").html());
                        if (isNaN(questionText[4])){
                            qnum = questionText[3];
                        } else {
                            qnum = question.slice(3,5);
                        }
                        var sid = $("#scenario_id").html();
                        var user = $("#user").html();
                        var resp = $("#input_ID{{i}}").val();
                        console.log("User:");
                        console.log(user);
                        console.log("Scenario ID:");
                        console.log(sid);
                        console.log("Question Number:");
                        console.log(qnum);
                        console.log("Response:");
                        console.log(resp);

                        let data = {'scenario': sid, 'question': qnum, 'response': resp, 'current_user': user};


                    }
                });
            {% endfor %}#}

            // copy ssh command to clipboard
            $("#copySSH").on("click", function(e) {
                let command = document.getElementById("sshCmd");
                command.select();
                document.execCommand("copy");
            });


            $("#Responses form button[type='submit']").on("click", function(e) {
                e.preventDefault();
                /*------------ POST request data -------------*/
                let csrf_token = $("#csrf_token").val(); //here I assume all questions share the same csrf (can't view page myself)
                let scenario = {{ id }}; //get scenario id from jinja variable
                let q = $(this).val(); //get question number from submit button pressed
                let response = $("#input_ID" + q).val(); //get proper response from "input_ID" plus question number
                /*--------------------------------------------*/
                let data = {'csrf_token': csrf_token, 'scenario': scenario, 'question': q, 'response': response}; //packaged data

                request = $.ajax({
                    type : 'POST',
                    url : "{{ url_for('dashboard.student_scenario', i=id) }}",
                    data : data
                });
                request.done(function(response) {
                    let q_label = $(response).filter("i");
                    let progress_q = $(response).find("#progress_q").html();
                    let progress_s = $(response).find("#progress_s").html();
                    $("#question_ID" + q + " i").replaceWith(q_label);
                    $("#progress_q").replaceWith(progress_q);
                    $("#progress_s").replaceWith(progress_s);
                });
                request.fail(function(response) {
                    alert("Something went wrong!");
                });
            });

        });
    </script>
{% endblock %}

edurange_refactored/templates/dashboard/student_scenario_new.html
{% extends "layout.html" %}
{% block content %}
    <link
            rel="stylesheet"
            type="text/css"
            href="{{ url_for('static', filename='build/student_scenario.bundle.css') }}"
    />
    <meta id="csrf_token" content="{{csrf_token()}}" />
<main class="student">
  <div id="student_scenario" scenario_id={{scenario_id}} uid="{{uid}}"></div>
</div>
</main>

{% endblock %}

{% block  js %}
<!-- development React scripts !!Replace with production scripts (below) for release!! -->
<!-- <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script> -->

<!-- production React scripts -->
<!-- <script src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script> -->

<script src="/static/build/student_scenario.bundle.js"></script>
{% endblock %}